---
- name: Playbook Write Test INI File
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Ensure "ansible_user=tony" is in section "[servers]" in specified file
   ini_file:
      path: /var/lib/buildkite-agent/tmp/inventory_test.ini
      section: servers
      option: ansible_user
      value: tony
      backup: yes
    delegate_to: localhost
