---
- name: Playbook Write Test INI File
  hosts: all
  connection: local
  gather_facts: false
  tasks:

  - name: Ensure "ansible_user=tony" is in section "[servers]" in specified file
    ini_file:
      path: /tmp/inventory_test.ini
      section: servers
      option: ansible_user
      value: tony
      backup: yes
