---
steps:
  - label: Clautomate Pipeline test ProRail
    command: echo "Hello ProRail!"

  - label: Run Pipeline test
    command: ansible-playbook -i "localhost," write_file.yml

  - label: End of test pipeline
    command: echo "Hiep Hoi"
